Dotfile repository, to be used with [[https://www.gnu.org/software/stow/][GNU Stow]].

* Package specific instructions
** Emacs
- Expects the emacswiki.org and hrs/sensible-defaults.el repos in ~/src/emacs/:
#+BEGIN_SRC sh
$ git clone -b master https://github.com/emacsmirror/emacswiki.org.git
#+END_SRC

#+BEGIN_SRC sh
$ git clone https://github.com/hrs/sensible-defaults.el.git
#+END_SRC
- M-x RET package-install-selected-packages RET
- Provides emacsd.service

** Tmux
- Needs [[https://github.com/tmux-plugins/tpm][TPM]]
#+BEGIN_SRC sh
$ git clone https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm
#+END_SRC
- Provides setup-tmux.service

** XConfig
- Provides comptond.service, redshiftd.service, udiskied.service, xss.service and xss-deactivate.timer
- bin/multibg.py taken from https://github.com/johannes87/multibg

** MPD
- Provides mpd.service
- bin/mpd_gen_playlists.zsh to create playlists for directories in mpd music library; respects an mpd_exclude.txt file there

* Stuff to do
** Bash
*** Make independent of distro
Easiest to just symlink both ".profile" and ".bash_profile" to same file?
*** Sort between .profile and .bashrc
*** Finally introduce some aliases
- xss-config to HOME="$HOME/dotfiles/xconfig/" xscreensaver-demo
- systemctl --user

** X config

** XMonad
*** More prefix-aware actions?
*** Feedback which submap is active?
*** GPU load in bar
*** processor frequencies in bar

** Emacs
*** move config to customize?
*** Expand cyphejor replacements

** General
*** Color switching
*** System status overview
