# /home/sam/.config/tmuxinator/dev.yml

name: dev
root: ~/

startup_pane: 1

windows:
  - shell:
      panes:
        - clr; fortune pratchett tao koan
        - clr; fortune pratchett tao koan
  - emacs: emacsclient -a '' -t -e '(progn (global-display-line-numbers-mode t) (switch-to-buffer "stuff.org") (split-window-below) (switch-to-buffer "*scratch*"))'
  - "~.":
      root: ~/dotfiles
      panes:
        - tmux movew -s dev:4 -t dev:5 ; tmux movew -s dev:3 -t dev:4 ; clr
        - clr; git status
  - man: tmux selectw -t dev:2 ; tmux selectw -t dev:1 ; clr
