git_repos = [
    "~/src/emacs/*/",
    "~/src/repos/*/",
    "~/dotfiles",
]

[commands]
"Make compose files" = "cd ~/src/repos/xcompose; make"
"Cabal update" = "cabal update; cd ~/src/repos/cabal/cabal-install; cabal install --overwrite-policy=always"
"xmobar update" = "cd ~/src/repos/xmobar; cabal install --overwrite-policy=always"
"xmonad recompile" = "xmonad --recompile"
