# /home/sam/.config/tmuxinator/dev.yml

name: dev
root: ~/

startup_pane: 1

windows:
  - shell:
	  panes:
		- empty
		- empty
  - emacs: emacsclient -a '' -t -e '(progn (switch-to-buffer "stuff.org") (split-window-below) (switch-to-buffer "*scratch*"))'
  - "~.":
	  root: ~/dotfiles
	  panes:
		- tmux move-window -s dev:4 -t dev:5 ; tmux move-window -s dev:3 -t dev:4 ; clr
		- git??
  - man: (tmux_dev_preselect_window.sh &); clr
